server:
  port: 7777
#  context-path: /uaa

spring:
  application:
    name: auth-server
  cloud:
    config:
      uri: http://microservicedocker-authserver:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://microservicedocker-eurekaserver:8761/eureka/

logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
      org.springframework.security: DEBUG