version: "3.7"
services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - 27017:27017
      volumes:
        - mongodb-data:/data/db
      networks:
        - mongodb_network
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo 0.0.0.0:27017/test --quiet
        interval: 60s
        timeout: 10s
        retries: 3
      restart: unless-stopped

    mongo-express:
      image: mongo-express
      container_name: mongo-express
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=root
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
      links:
        - mongodb
      depends_on:
        - mongodb
      networks:
        - mongodb_network
      ports:
        - 27000:8081
      healthcheck:
        test:  wget --quiet --tries=3 --spider http://admin:admin@0.0.0.0:8081 || exit 1
        interval: 60s
        timeout: 10s
        retries: 3

volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb_network:
    name: mongodb_network

