FROM java:8

MAINTAINER oopsmails.com

COPY files/spring-cloud-microservices-zuulproxy-1.0-SNAPSHOT.jar /opt/lib/microservice-docker/microservice-docker-zuul-server.jar

# ENV SPRING_APPLICATION_JSON='{"eureka": {"client": {"serviceUrl": {"defaultZone": "http://microservicedocker-eurekaserver:8761/eureka/"}}}, "spring": {"cloud": {"config": {"uri": "http://microservicedocker-configserver:8888"}}}}'
ENV SPRING_APPLICATION_JSON=' \
{ \
    "spring": \
    { \
        "application": \
        { \
            "name": "proxy-service" \
        }, \
        "cloud": \
        { \
            "config": \
            { \
                "uri": "http://microservicedocker-configserver:8888" \
            } \
        } \
    } \
}'


ENTRYPOINT ["/usr/bin/java"]

CMD ["-jar", "/opt/lib/microservice-docker/microservice-docker-zuul-server.jar"]

EXPOSE 9999