FROM java:8

MAINTAINER oopsmails.com

COPY files/spring-cloud-microservices-configserver-1.0-SNAPSHOT.jar /opt/lib/microservice-docker/microservice-docker-config-server.jar
COPY files/config-repo /var/lib/microservice-docker/config-repo

ENV SPRING_APPLICATION_JSON='{"management": {"security": {"enabled": false}}, "spring": {"profiles": {"active": "native"}, "cloud": {"config": {"server": \
	{"native": {"searchLocations": "/var/lib/microservice-docker/config-repo"}}}}}}'

ENTRYPOINT ["/usr/bin/java"]

CMD ["-jar", "/opt/lib/microservice-docker/microservice-docker-config-server.jar"]

VOLUME /var/lib/microservice-docker/config-repo

EXPOSE 8888