FROM java:8

MAINTAINER oopsmails.com

COPY files/spring-cloud-microservices-authserver-1.0-SNAPSHOT.jar /opt/lib/microservice-docker/microservice-docker-auth-server.jar

ENV SPRING_APPLICATION_JSON=' \
{ \
    "spring": \
    { \
        "application": \
        { \
            "name": "auth-server" \
        }, \
        "cloud": \
        { \
            "config": \
            { \
                "uri": "http://microservicedocker-configserver:8888" \
            } \
        } \
    } \
}'


ENTRYPOINT ["/usr/bin/java"]

CMD ["-jar", "/opt/lib/microservice-docker/microservice-docker-auth-server.jar"]

EXPOSE 7777