apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-mgmt-deploy
  labels:
    app: config-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-mgmt
  template:
    metadata:
      labels:
        app: config-mgmt
    spec:
      containers:
        - name: config-mgmt
          image: configmgmt:1.0.0
          envFrom:
            - configMapRef:
                name: banner-config-preprod
          ports:
            - containerPort: 8080
