apiVersion: v1
kind: ConfigMap
metadata:
  name: banner-config-preprod
  namespace: default
data:
  app.env.label: Pre-production
  app.env.color: purple

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-mgmt-deploy
  labels:
    app: config-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-mgmt
  template:
    metadata:
      labels:
        app: config-mgmt
    spec:
      containers:
        - name: config-mgmt
          image: configmgmt:1.0.0
          envFrom:
            - configMapRef:
                name: banner-config-preprod
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: config-mgmt-service
spec:
  selector:
    app: config-mgmt
  ports:
    - port: 8080
      nodePort: 30001
  type: NodePort
